baseURL = "https://sim.ilitu.de/"
languageCode = "en-us"
title = "similitude"
theme = "base16"
markup.highlight.noClasses = false
[params]
	commentsServer = "https://comments.sim.ilitu.de" #"http://localhost:8000"
