baseURL = "https://sim.ilitu.de/"
languageCode = "en-us"
title = "similitude"
# theme = "base16"
[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
	noClasses = false
[params]
	commentsServer = "https://comments.sim.ilitu.de"
[module]
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'node_modules/@fontsource/source-code-pro/files'
  target = 'static/fonts/files'
	includeFiles = '*.woff?'
